name: Ruby

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1.1.2
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: gem install bundler && bundle install --jobs 4 --retry 3
    - name: Set up database
      run: bundle exec rails db:setup
    - name: Ruby Tests
      run: bundle exec rails test
    - name: RuboCop
      run: bundle exec rubocop
