name: Ruby

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1.1.2
      with:
        ruby-version: 2.7
    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle config frozen true
        bundle install --jobs 4 --retry 3
    - name: Set up database
      run: bundle exec rails db:setup
    - name: Ruby Tests
      run: bundle exec rails test
    - name: System Tests
      run: bundle exec rails app:test:system
    - name: RuboCop
      run: bundle exec rubocop
